[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "mkdir -p downloads",
  "ffmpeg -version || echo 'FFmpeg not found'"
]

[start]
cmd = "python app.py"
